### ISSUE TITLE
Command to dry check the configuration before starting the server

### ISSUE THREAD

**Issue by kabirbaidhya** [kabirbaidhya/pglistend#13]
It would be really helpful to be able to dry check or test if the configurations (especially db credentials)  are okay before starting the service. Just to know beforehand if the configs are okay or not. 

Something similar to what we can do with `sudo nginx -t`
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

In pglistend we can have something like
```
pglisten  --dry-check --config=/etc/pglistend/config.yml
```
This would either print `OK` or errors/warnings.

**Comment by kabirbaidhya** [comment]
@sanjeevkpandit Let me know if you have any suggestions on this.

**Comment by trourance** [comment]
+1

**Comment by sanjeevkpandit** [comment]
@kabirbaidhya I will look into this.
