### ISSUE TITLE
Do not overwrite/replace the config file on re-installation

### ISSUE THREAD

**Issue by kabirbaidhya** [kabirbaidhya/pglistend#14]
When you have already installed and setup/configured the service, try running the setup script again; it would replace the config file `/etc/pglistend/config.yml` with a fresh generated file. 

This should not happen. Or, at least it should keep the copy of original config in case files are overwritten.

**Comment by anusha5695** [comment]
@kabirbaidhya is this open for PR?

**Comment by kabirbaidhya** [comment]
@anusha5695 Yes, it is. 

Just a heads up that - I had worked on this project few years back so there might be chances that things aren't in place. Feel free to ask any queries if you run into issues. Thanks!
