### ISSUE TITLE
Configuration keys not overriden

### ISSUE THREAD

**Issue by trourance** [kabirbaidhya/pglistend#15]
Hi,
It is related to the issue #11 where you wrote:

> If you put these under default you can just skip these keys in your database configuration file. But if you put these keys they'd override the default ones.

However, I've tried and the port, for example, is not overriden by the one in the second configuration file.

config.yml:
```python
default:
    connection:
        host: localhost
        port: 5432

# Include configuration files database connections you want to use
connections:
   - /etc/pglistend/pglistend-connection.yml
```

pglistend-connection.yml:
```python
connection:
     user: 'postgres'
     password: 'postgres'
     host: localhost
     port: 5444
     database: 'test_pglistend'
     max: 1
     idleTimeoutMillis: 10000

```
I get the following in the logs:
`pglistend[11577]: Loaded configuration file: /etc/pglistend/config.yml`
`pglistend[11577]: Loaded configuration file: /etc/pglistend/pglistend-connection.yml`
`pglistend[11577]: Error: connect ECONNREFUSED 127.0.0.1:5432`

**Comment by kabirbaidhya** [comment]
Okay, will look into this.

**Comment by trourance** [comment]
Hi guys,
This bug has been reported almost one year ago. Are you still working on this project ?

**Comment by kabirbaidhya** [comment]
Hi @trourance,

Sorry, we got busy and haven't got a chance to look into this. If you think there's a quick fix and could do a PR, please do and we can do a patch. Because right now it's difficult to guarantee if this is going to be fixed any sooner.

Thanks
