### ISSUE TITLE
Configuration not always loaded

### ISSUE THREAD

**Issue by trourance** [kabirbaidhya/pglistend#17]
Hi,

I made some tries and it seems that the configuration files are not always reloaded when you stop and start the daemon.
Sometimes, you have to restart it several times for your changes to be applied or you have to wait more some kind of delay after stopping it.

**Comment by kabirbaidhya** [comment]
Hi @fluancefg thanks for reporting the issue. 
Sorry, we have been a little busy lately, so we won't be able to check this at the moment and this might take time. However, if you want a quick fix you may send a pull request and we can look into it.

**Comment by cgoodrich** [comment]
@kabirbaidhya I've been working with this thing again...it's awesome

**Comment by cgoodrich** [comment]
@kabirbaidhya I've been working with this thing again...it's awesome

**Comment by kabirbaidhya** [comment]
Great. Thanks @cgoodrich.
