### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by trourance** [kabirbaidhya/pglistend#9]
Hi,
I've tried to install and launch the application, but I get the following error:

```
sudo pglisten setup-daemon
  File "/usr/lib/node_modules/pglistend/setup/setup.py", line 121
    print cmd_t('> {}'.format(cmd))
              ^
SyntaxError: invalid syntax
Setup could not be completed.
```

**Comment by kabirbaidhya** [comment]
Hi @fluancefg Can you try running this alternative script and see if you still get the same error?

```
curl https://raw.githubusercontent.com/kabirbaidhya/pglistend/master/setup/setup.py | sudo python
```

**Comment by kabirbaidhya** [comment]
Looking at the error message `SyntaxError: invalid syntax` I think the error is due to python version. 

Can you please run `python --version` and see if its 3.x.x or 2.7.x? Actually, we've built it based upon python 2.7 so I think we need to do a patch if it doesn't work when python3 is default.

**Comment by trourance** [comment]
Same result

2017-03-28 17:36 GMT+02:00 Kabir <notifications@github.com>:

**Comment by trourance** [comment]
This is exactly what I was thinking. However, I did not find any
requirements or any information about Python version on the website.

As I'm running it on Arch Linux, I have Python 3.5.2 installed.

I'll try to run it in a virtual python environment.

2017-03-28 17:45 GMT+02:00 Kabir <notifications@github.com>:

**Comment by kabirbaidhya** [comment]
Okay, I'll fix this and will do a patch shortly. Thanks.
